name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Run Lints and Tests
    runs-on: ubuntu-latest

    # Database service for running integration tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        entrypoint: docker-entrypoint.sh
        command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      # Set up Rust toolchain for running tests
      - name: Set up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      # Run Cargo tests (requires SQLx offline mode for query verification and a running Postgres instance)
      - name: Run Tests
        env:
          SQLX_OFFLINE: true
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
        run: make test
